name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
    - uses: actions/checkout@v2
    - name: docker build and push
      run: |
       docker build -t 3iamlucifer12/website -f Dockerfile .
       docker push 3iamlucifer12/website


deployweb:
  needs: [build]
  runs-on: ubuntu-latest

  steps:
    - name: deploy build
    run: |
      docker run -d --name web -p 7777:80 3iamlucifer12/website
