name: merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop, main  ]
  pull_request: 
     branches: [ main ]
  
jobs:
  auto-merge:

    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Auto-Merge Pull Request
      uses: reitermarkus/automerge@v2.0.0

     
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
